
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Button btnHallo;
	
	private global::Gtk.Button BtnJetzthier;
	
	private global::Gtk.Button BtnNochhier;
	
	private global::Gtk.Button BtnFinish;
	
	private global::Gtk.Button BtnFortsetzung;
	
	private global::Gtk.Button BtnEnde;
	
	private global::Gtk.Button BtnEndeEnde;
	
	private global::Gtk.Button BtnEndeEndeEnde;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnHallo = new global::Gtk.Button ();
		this.btnHallo.CanFocus = true;
		this.btnHallo.Name = "btnHallo";
		this.btnHallo.UseUnderline = true;
		this.btnHallo.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.fixed1.Add (this.btnHallo);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnHallo]));
		w1.X = 187;
		w1.Y = 135;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BtnJetzthier = new global::Gtk.Button ();
		this.BtnJetzthier.CanFocus = true;
		this.BtnJetzthier.Name = "BtnJetzthier";
		this.BtnJetzthier.UseUnderline = true;
		this.BtnJetzthier.Label = global::Mono.Unix.Catalog.GetString ("Jetzt hier");
		this.fixed1.Add (this.BtnJetzthier);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BtnJetzthier]));
		w2.X = 181;
		w2.Y = 378;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BtnNochhier = new global::Gtk.Button ();
		this.BtnNochhier.CanFocus = true;
		this.BtnNochhier.Name = "BtnNochhier";
		this.BtnNochhier.UseUnderline = true;
		this.BtnNochhier.Label = global::Mono.Unix.Catalog.GetString ("Noch hier");
		this.fixed1.Add (this.BtnNochhier);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BtnNochhier]));
		w3.X = 586;
		w3.Y = 138;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BtnFinish = new global::Gtk.Button ();
		this.BtnFinish.CanFocus = true;
		this.BtnFinish.Name = "BtnFinish";
		this.BtnFinish.UseUnderline = true;
		this.BtnFinish.Label = global::Mono.Unix.Catalog.GetString ("Finish");
		this.fixed1.Add (this.BtnFinish);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BtnFinish]));
		w4.X = 597;
		w4.Y = 374;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BtnFortsetzung = new global::Gtk.Button ();
		this.BtnFortsetzung.CanFocus = true;
		this.BtnFortsetzung.Name = "BtnFortsetzung";
		this.BtnFortsetzung.UseUnderline = true;
		this.BtnFortsetzung.Label = global::Mono.Unix.Catalog.GetString ("Geht noch weiter");
		this.fixed1.Add (this.BtnFortsetzung);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BtnFortsetzung]));
		w5.X = 560;
		w5.Y = 374;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BtnEnde = new global::Gtk.Button ();
		this.BtnEnde.CanFocus = true;
		this.BtnEnde.Name = "BtnEnde";
		this.BtnEnde.UseUnderline = true;
		this.BtnEnde.Label = global::Mono.Unix.Catalog.GetString ("Ende?");
		this.fixed1.Add (this.BtnEnde);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BtnEnde]));
		w6.X = 390;
		w6.Y = 261;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BtnEndeEnde = new global::Gtk.Button ();
		this.BtnEndeEnde.CanFocus = true;
		this.BtnEndeEnde.Name = "BtnEndeEnde";
		this.BtnEndeEnde.UseUnderline = true;
		this.BtnEndeEnde.Label = global::Mono.Unix.Catalog.GetString ("Ok jetzt is Ende");
		this.fixed1.Add (this.BtnEndeEnde);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BtnEndeEnde]));
		w7.X = 361;
		w7.Y = 261;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BtnEndeEndeEnde = new global::Gtk.Button ();
		this.BtnEndeEndeEnde.CanFocus = true;
		this.BtnEndeEndeEnde.Name = "BtnEndeEndeEnde";
		this.BtnEndeEndeEnde.UseUnderline = true;
		this.BtnEndeEndeEnde.Label = global::Mono.Unix.Catalog.GetString ("Ok Ende Ende");
		this.fixed1.Add (this.BtnEndeEndeEnde);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BtnEndeEndeEnde]));
		w8.X = 368;
		w8.Y = 261;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 864;
		this.DefaultHeight = 524;
		this.BtnJetzthier.Hide ();
		this.BtnNochhier.Hide ();
		this.BtnFinish.Hide ();
		this.BtnFortsetzung.Hide ();
		this.BtnEnde.Hide ();
		this.BtnEndeEnde.Hide ();
		this.BtnEndeEndeEnde.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnHallo.Clicked += new global::System.EventHandler (this.BtnHallo_Clicked);
		this.BtnJetzthier.Clicked += new global::System.EventHandler (this.BtnJetzthier_Clicked);
		this.BtnNochhier.Clicked += new global::System.EventHandler (this.BtnNochhier_Clicked);
		this.BtnFinish.Clicked += new global::System.EventHandler (this.BtnFinish_Clicked);
		this.BtnFortsetzung.Clicked += new global::System.EventHandler (this.BtnFortsetzung_clicked);
		this.BtnEnde.Clicked += new global::System.EventHandler (this.BtnEnde_Clicked);
		this.BtnEndeEnde.Clicked += new global::System.EventHandler (this.BtnEndeEnde_Clicked);
		this.BtnEndeEndeEnde.Clicked += new global::System.EventHandler (this.BtnEndeEndeEnde_Clicked);
	}
}
